.github/workflows/auto-publish.yml
.pr-preview.json
index.html

This is basically just a concatenation of https://darobin.github.io/pup/ with a subset of https://w3cping.github.io/privacy-threat-model/. I didn't edit the content at all.

Add an initial draft for the Principles document

---

README.md

I didn't attempt to put the lists in any sort of order, except to put the chairs next to the WHATWG SG.

Split kinds of experts out of the constituencies list.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/17.html" title="Last updated on Jul 28, 2021, 4:16 PM UTC (a3d9358)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/17/4f5a63c...a3d9358.html" title="Last updated on Jul 28, 2021, 4:16 PM UTC (a3d9358)">Diff</a>

Update the Status of this Document to be more in line with other W3C documents.

---

index.html

Provides a third alternative to #32 and #43, based on the [discussion on 2021-09-08](https://github.com/w3ctag/privacy-principles/blob/main/meetings/2021-09-08-minutes.md#redefining-party).
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/44.html#parties" title="Last updated on Sep 14, 2021, 11:41 PM UTC (fd77d35)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/44/dc93f38...jyasskin:fd77d35.html" title="Last updated on Sep 14, 2021, 11:41 PM UTC (fd77d35)">Diff</a>

Define a party as whatever a person understands as a single thing.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/45.html" title="Last updated on Sep 22, 2021, 4:40 PM UTC (f1267b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/45/d6c7a46...f1267b9.html" title="Last updated on Sep 22, 2021, 4:40 PM UTC (f1267b9)">Diff</a>

Rewrite SotD according to style guide

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/46.html" title="Last updated on Sep 22, 2021, 4:55 PM UTC (2765177)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/46/d6c7a46...2765177.html" title="Last updated on Sep 22, 2021, 4:55 PM UTC (2765177)">Diff</a>

Apply style guide to intro

---

index.html

this is an experimental PR to demonstrate what it might look like to change "users" to "people" across thd document. 
Referencing #52
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/69.html" title="Last updated on Nov 3, 2021, 2:49 PM UTC (5b75327)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/69/9cc8254...5b75327.html" title="Last updated on Nov 3, 2021, 2:49 PM UTC (5b75327)">Diff</a>

users -> people

---

index.html

Add a reference in References section.
Link from "powerlessness and loss of agency" in "unexpected profiling" section.
Fixes #66
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/95.html" title="Last updated on Jan 11, 2022, 7:35 PM UTC (c8503d6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/95/8e8b804...c8503d6.html" title="Last updated on Jan 11, 2022, 7:35 PM UTC (c8503d6)">Diff</a>

Reference to Pew Research report

---

index.html

I tried to incorporate Robin's goal for a coherent narrative instead of just a specification, and my goal of including non-data privacy. I left lots of issues where there's still more work to do to clean up the text, but hopefully the direction is clear and matches y'all's intentions.
Fixes #89.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/94.html" title="Last updated on Jan 12, 2022, 7:17 PM UTC (9479374)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/94/9fd56a9...9479374.html" title="Last updated on Jan 12, 2022, 7:17 PM UTC (9479374)">Diff</a>

Reorganize the document to flow better

---

index.html

> Re: section 1: “The goal of this document is to define principles that may prove useful in developing technology and policy that relate to privacy and personal data”, it would be helpful if we could elevate the goal to “define privacy principles for Web technologies” (or similar)
Done.
> Re: section 2.2: Perhaps we could leave out the point about data paternalism as the explanation of user agent duties make it clear that is not what is envisaged.
Done, and I removed the reference from the autonomy section.
> Also, is “duty of discretion” the right term?
This comes from [Taking Trust Seriously in Privacy Law](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2655719), which is cited above the list of duties. I've tried to adjust the text to match that definition of discretion better, …

Fix some of sandandsnow's comments from #94.

---

index.html
rewrite.md

This is the follow-up rejig to make the document narrative. I think I have found a way (though some parts still need editing).
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/102.html" title="Last updated on Jan 26, 2022, 10:03 PM UTC (5390e58)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/102/45e86ea...5390e58.html" title="Last updated on Jan 26, 2022, 10:03 PM UTC (5390e58)">Diff</a>

Narrative & Rules

---

index.html

I think this matches our [discussion](https://github.com/w3ctag/privacy-principles/blob/main/meetings/2022-01-26-minutes.md#the-pr) yesterday.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/115.html" title="Last updated on Feb 1, 2022, 9:12 PM UTC (13cbe97)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/115/c27e7b3...jyasskin:13cbe97.html" title="Last updated on Feb 1, 2022, 9:12 PM UTC (13cbe97)">Diff</a>

Clarify the cross-site identity principle.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/116.html#how-this-document-fits-in" title="Last updated on Feb 2, 2022, 5:43 PM UTC (0ea3f73)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/116/c27e7b3...jyasskin:0ea3f73.html" title="Last updated on Feb 2, 2022, 5:43 PM UTC (0ea3f73)">Diff</a>

Explain that we're covering just one of the ethical web principles.

---

index.html

Editing down the text to simplify language.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/123.html" title="Last updated on Feb 9, 2022, 1:43 PM UTC (f6522a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/123/ef51159...f6522a4.html" title="Last updated on Feb 9, 2022, 1:43 PM UTC (f6522a4)">Diff</a>

A couple of minor edits

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/127.html#unwanted-information" title="Last updated on Feb 16, 2022, 5:11 PM UTC (b8e2f4e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/127/a1b3a33...b8e2f4e.html" title="Last updated on Feb 16, 2022, 5:11 PM UTC (b8e2f4e)">Diff</a>

Unwanted information principle

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/128.html" title="Last updated on Feb 16, 2022, 5:27 PM UTC (f8c7af7)">Preview</a> (<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/128.html#opt-in-out" title="#opt-in-out">#opt-in-out</a>) (<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/128.html#principles-for-consent-withdrawal-of-consent-opt-outs-and-objections" title="#principles-for-consent-withdrawal-of-consent-opt-outs-and-objections">#principles-for-cons…</a>) | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/128/a1b3a33...f8c7af7.html" title="Last updated on Feb 16, 2022, 5:27 PM UTC (f8c7af7)">Diff</a>

Consent principles and some related edits to the consent section

---

index.html

There was no text.
https://github.com/w3ctag/privacy-principles/issues/131
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/138.html" title="Last updated on Mar 9, 2022, 5:06 PM UTC (bc490fc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/138/1876fd0...bc490fc.html" title="Last updated on Mar 9, 2022, 5:06 PM UTC (bc490fc)">Diff</a>

Suggest removing "principle re influence and manipulation"

---

index.html

I kept it at a relatively high level, but hopefully enough that people _can_ do something with it.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/130.html#collective-privacy" title="Last updated on Mar 17, 2022, 10:18 PM UTC (f7dc72f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/130/a1b3a33...f7dc72f.html" title="Last updated on Mar 17, 2022, 10:18 PM UTC (f7dc72f)">Diff</a>

Collective principle

---

index.html

Fixes #73.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/105.html#balancing" title="Last updated on Mar 30, 2022, 12:35 AM UTC (2447bd8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/105/e351f39...jyasskin:2447bd8.html" title="Last updated on Mar 30, 2022, 12:35 AM UTC (2447bd8)">Diff</a>

Discuss tensions between principles.

---

index.html

As discussed last week here is a first draft of notifications principles.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/132.html#principles-for-notifications-and-interruptions" title="Last updated on Apr 6, 2022, 11:10 PM UTC (74ef923)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/132/92510f5...74ef923.html" title="Last updated on Apr 6, 2022, 11:10 PM UTC (74ef923)">Diff</a>

Added notifications principles

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/141.html#non-retaliation" title="Last updated on Apr 13, 2022, 4:20 PM UTC (e54e9ad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/141/1ed423a...e54e9ad.html" title="Last updated on Apr 13, 2022, 4:20 PM UTC (e54e9ad)">Diff</a>

Add a non-retaliation principle

---

index.html

WARNING: This is a PR on a PR (#133)
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/147.html" title="Last updated on Apr 20, 2022, 4:22 PM UTC (e8b46f4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/147/95d6a16...e8b46f4.html" title="Last updated on Apr 20, 2022, 4:22 PM UTC (e8b46f4)">Diff</a>

Rework pes removed text

---

index.html

We probably shouldn't merge this until we've done our first pass on the document & adjusted it accordingly.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/14.html" title="Last updated on Jul 7, 2021, 4:17 PM UTC (dfaf920)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/14/6e8a30a...dfaf920.html" title="Last updated on Jul 7, 2021, 4:17 PM UTC (dfaf920)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/14.html" title="Last updated on Apr 20, 2022, 4:50 PM UTC (eb9668f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/14/cc7bdd2...eb9668f.html" title="Last updated on Apr 20, 2022, 4:50 PM UTC (eb9668f)">Diff</a>

Make the orange box go away.

---

index.html

Please, think of the brains.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/148.html" title="Last updated on Apr 20, 2022, 5:07 PM UTC (00cc88d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/148/2b12cea...00cc88d.html" title="Last updated on Apr 20, 2022, 5:07 PM UTC (00cc88d)">Diff</a>

Alphabetize Appendix B (High-Level Threats)

---

index.html

For discussion on the Privacy Task Force call today.  The text would need a lot of polish, but eager to get feed back on the effort to reorg, etc
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/133.html#data" title="Last updated on Apr 20, 2022, 11:04 PM UTC (5b39144)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/133/ff66160...5b39144.html" title="Last updated on Apr 20, 2022, 11:04 PM UTC (5b39144)">Diff</a>

first go at reworking private data section into discrete principles

---

index.html

As discussed in today's meeting -- make it clear that the first party
is the party that has control of the person's (user's) data.  (The
editor of site content or the administrator of the site's hosting
service is not necessarily the first party.)
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/143.html" title="Last updated on Apr 21, 2022, 5:15 PM UTC (74e723e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/143/ff66160...74e723e.html" title="Last updated on Apr 21, 2022, 5:15 PM UTC (74e723e)">Diff</a>

Wording on control of information

---

index.html

some text for an initial discussion on sign-in and #120
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/173.html" title="Last updated on Aug 11, 2022, 2:10 PM UTC (a8605cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/173/0797516...a8605cf.html" title="Last updated on Aug 11, 2022, 2:10 PM UTC (a8605cf)">Diff</a>

text for discussion on sign-in

---

index.html

This takes modified language from @ianbjacobs.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/179.html" title="Last updated on Aug 31, 2022, 4:06 PM UTC (2d5ba0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/179/76b45e0...2d5ba0c.html" title="Last updated on Aug 31, 2022, 4:06 PM UTC (2d5ba0c)">Diff</a>

Make the impact data combination on de-identification clearer (fixes #146)

---

index.html

separate PR just on minimization
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/183.html#data" title="Last updated on Sep 28, 2022, 8:02 PM UTC (edd209c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/183/5207f3b...edd209c.html" title="Last updated on Sep 28, 2022, 8:02 PM UTC (edd209c)">Diff</a>

Minimization

---

index.html

Related: #172
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/193.html" title="Last updated on Nov 16, 2022, 11:46 PM UTC (20de140)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/193/90459b8...20de140.html" title="Last updated on Nov 16, 2022, 11:46 PM UTC (20de140)">Diff</a>

First draft of audiences section

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/199.html" title="Last updated on Nov 30, 2022, 5:46 PM UTC (6eee42e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/199/3db17d2...6eee42e.html" title="Last updated on Nov 30, 2022, 5:46 PM UTC (6eee42e)">Diff</a>

Add ephemeral or anonymous identity

---

index.html

addresses #204
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/206.html" title="Last updated on Dec 10, 2022, 6:14 PM UTC (8843ddd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/206/f4cf6de...8843ddd.html" title="Last updated on Dec 10, 2022, 6:14 PM UTC (8843ddd)">Diff</a>

adding missing references on harassment

---

index.html

Give more context to why we're talking about recognition, fixes #200 includes #186.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/201.html#identity" title="Last updated on Dec 14, 2022, 5:08 PM UTC (228a859)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/201/94428dc...228a859.html" title="Last updated on Dec 14, 2022, 5:08 PM UTC (228a859)">Diff</a>

Editorial pass over identity

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/182.html#information" title="Last updated on Dec 14, 2022, 5:20 PM UTC (4734397)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/182/2380f22...jyasskin:4734397.html" title="Last updated on Dec 14, 2022, 5:20 PM UTC (4734397)">Diff</a>

Try to explain how new APIs can or can't be justified based on old ones.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/207.html#recognition-types" title="Last updated on Dec 14, 2022, 5:56 PM UTC (949e049)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/207/73cdb49...jyasskin:949e049.html" title="Last updated on Dec 14, 2022, 5:56 PM UTC (949e049)">Diff</a>

Tweaks to the identity section after #201.

---

index.html

This is a batch editorial pass based on reading the doc from the top and looking for parts that don't come across clearly. I stopped before _§2.7 Collective Privacy_.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/208.html" title="Last updated on Jan 4, 2023, 5:15 PM UTC (6cbaba8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/208/31fdce5...6cbaba8.html" title="Last updated on Jan 4, 2023, 5:15 PM UTC (6cbaba8)">Diff</a>

Welcome to 2023 Editorial Pass

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/158.html#example-preventing-profiling" title="Last updated on Jan 4, 2023, 5:59 PM UTC (fe3db6f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/158/0b159b4...jyasskin:fe3db6f.html" title="Last updated on Jan 4, 2023, 5:59 PM UTC (fe3db6f)">Diff</a>

Tension within anti-profiling designs

---

index.html

I don't see anything in this comment that urgently needs to migrate to the rest of the document. If something's still important, it should be in an issue rather than a comment.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/211.html" title="Last updated on Jan 17, 2023, 11:22 PM UTC (80ba1d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/211/0c8f4e5...jyasskin:80ba1d8.html" title="Last updated on Jan 17, 2023, 11:22 PM UTC (80ba1d8)">Diff</a>

Delete a comment.

---

index.html

Fixes #168. I made two minor tweaks to @mnot's suggested wording.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/210.html" title="Last updated on Jan 18, 2023, 8:11 PM UTC (87319f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/210/0c8f4e5...jyasskin:87319f6.html" title="Last updated on Jan 18, 2023, 8:11 PM UTC (87319f6)">Diff</a>

Improve explanation of how this document relates to laws and regulation.

---

index.html

Thanks @mnot!
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/214.html#bib-new-chicago-school" title="Last updated on Jan 19, 2023, 1:17 AM UTC (1665ecf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/214/a1d8862...jyasskin:1665ecf.html" title="Last updated on Jan 19, 2023, 1:17 AM UTC (1665ecf)">Diff</a>

Cite The New Chicago School instead of Code.

---

index.html

Comments and suggestions in response to https://github.com/w3ctag/privacy-principles/issues/165
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/216.html#ancillary-uses" title="Last updated on Feb 23, 2023, 12:45 AM UTC (1b585f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/216/a1d8862...1b585f1.html" title="Last updated on Feb 23, 2023, 12:45 AM UTC (1b585f1)">Diff</a>

Revisions and concisions around ancillary data use

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/227.html#user-agent-recognition" title="Last updated on Mar 14, 2023, 12:23 AM UTC (9335f16)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/227/d52ee70...jyasskin:9335f16.html" title="Last updated on Mar 14, 2023, 12:23 AM UTC (9335f16)">Diff</a>

Fix #224: Mention harm from partially blocking cross-context recognition.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/234.html" title="Last updated on Mar 23, 2023, 12:19 AM UTC (024d562)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/234/d759205...jyasskin:024d562.html" title="Last updated on Mar 23, 2023, 12:19 AM UTC (024d562)">Diff</a>

Remove some sarcasm about FIPs.

---

index.html

Suggested by @jbradleychen.
This is a minimal change, but the paragraph might benefit from being simplified in other ways.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/237.html" title="Last updated on Mar 23, 2023, 11:00 PM UTC (16f6f74)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/237/fe705f6...jyasskin:16f6f74.html" title="Last updated on Mar 23, 2023, 11:00 PM UTC (16f6f74)">Diff</a>

Remove "unprecedented": these concentrations of power have precedents.

---

index.html

This makes it clear that this isn't legal advice or a specific position about the GDPR but an understanding of how an automated signal can intersect with specific data protection approaches. Fixes #232.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/243.html" title="Last updated on Apr 12, 2023, 1:59 PM UTC (d0e96e0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/243/5690bcc...d0e96e0.html" title="Last updated on Apr 12, 2023, 1:59 PM UTC (d0e96e0)">Diff</a>

Make it clear that this is a general statement, not about the GDPR

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/246.html" title="Last updated on Apr 7, 2023, 12:26 AM UTC (cb5fdaa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/246/2832c2c...jyasskin:cb5fdaa.html" title="Last updated on Apr 7, 2023, 12:26 AM UTC (cb5fdaa)">Diff</a>

Try to improve the wording around consent indicators.

---

index.html

See #257
***
<a href="https://pr-preview.s3.amazonaws.com/chrisn/privacy-principles/pull/258.html" title="Last updated on Apr 24, 2023, 5:03 PM UTC (02ee2f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/258/4e4732c...chrisn:02ee2f7.html" title="Last updated on Apr 24, 2023, 5:03 PM UTC (02ee2f7)">Diff</a>

Add link to 'site' definition

---

index.html

See #253. With this change I've tried to consolidate discussion of goals and purposes of the document under "How This Document Fits In", as well as consolidate the text on asymmetries of power. On the latter, I ended up leaving the description of information flows in place, as it sets up the next paragraph on "Information is power".
***
<a href="https://pr-preview.s3.amazonaws.com/chrisn/privacy-principles/pull/262.html" title="Last updated on Apr 27, 2023, 7:20 PM UTC (2c9c073)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/262/42a20be...chrisn:2c9c073.html" title="Last updated on Apr 27, 2023, 7:20 PM UTC (2c9c073)">Diff</a>

Restructure introduction sections

---

index.html

Fixes the rest of #253.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/267.html" title="Last updated on May 4, 2023, 12:42 AM UTC (eb62842)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/267/6b09507...jyasskin:eb62842.html" title="Last updated on May 4, 2023, 12:42 AM UTC (eb62842)">Diff</a>

chrisn's tweaks to the introduction

---

index.html

- Use [[Citation-Style]] instead of just links.
- Use consistent language around violating norms.
Fixes #256.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/266.html#balancing" title="Last updated on May 10, 2023, 4:03 PM UTC (7575d92)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/266/6b09507...jyasskin:7575d92.html" title="Last updated on May 10, 2023, 4:03 PM UTC (7575d92)">Diff</a>

Tweaks to the Incorporating section

---

index.html

Fixes #255.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/265.html" title="Last updated on May 4, 2023, 12:07 AM UTC (706c23a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/265/6b09507...jyasskin:706c23a.html" title="Last updated on May 4, 2023, 12:07 AM UTC (706c23a)">Diff</a>

s/People's Agents/User Agents/, and tweak a sentence in that section.

---

index.html

Reformulated to emphasise that disloyalty has to be detrimental to people. Fixes #241.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/269.html" title="Last updated on May 31, 2023, 4:22 PM UTC (fc39669)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/269/a78f4f1...fc39669.html" title="Last updated on May 31, 2023, 4:22 PM UTC (fc39669)">Diff</a>

Make it clearer that disloyalty must be detrimental to people

---

index.html

Understanding that is important enough to include another sentence, I think.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/privacy-principles/pull/274.html" title="Last updated on Jun 27, 2023, 4:39 AM UTC (bcd7db7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/274/5286a4e...martinthomson:bcd7db7.html" title="Last updated on Jun 27, 2023, 4:39 AM UTC (bcd7db7)">Diff</a>

Fingerprinting requires that attributes be aggregated

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/292.html" title="Last updated on Jun 28, 2023, 2:44 PM UTC (0f9d27a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/292/86d1c1f...0f9d27a.html" title="Last updated on Jun 28, 2023, 2:44 PM UTC (0f9d27a)">Diff</a>

Exemplify good style, fix #278

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/294.html" title="Last updated on Jun 28, 2023, 3:07 PM UTC (a4acf19)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/294/86d1c1f...a4acf19.html" title="Last updated on Jun 28, 2023, 3:07 PM UTC (a4acf19)">Diff</a>

Registries are bad, fix #272

---

index.html

This is intended to supersede #238.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/296.html" title="Last updated on Jun 28, 2023, 6:02 PM UTC (c724a30)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/296/86d1c1f...c724a30.html" title="Last updated on Jun 28, 2023, 6:02 PM UTC (c724a30)">Diff</a>

Revisit global opt out, fix #231

---

index.html

Fixes #283
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/336.html" title="Last updated on Jul 19, 2023, 4:48 PM UTC (3f137d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/336/33628fa...3f137d1.html" title="Last updated on Jul 19, 2023, 4:48 PM UTC (3f137d1)">Diff</a>

Remove unclear point about revoking information

---

index.html

Closes #282.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/338.html" title="Last updated on Jul 21, 2023, 1:28 PM UTC (431bf87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/338/5e1282b...431bf87.html" title="Last updated on Jul 21, 2023, 1:28 PM UTC (431bf87)">Diff</a>

Add identifiers to sensitive data list

---

index.html

fixes issue #285
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/337.html" title="Last updated on Jul 19, 2023, 5:24 PM UTC (52cfc3b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/337/5e1282b...52cfc3b.html" title="Last updated on Jul 19, 2023, 5:24 PM UTC (52cfc3b)">Diff</a>

Remove ", notably against timing or k-anonymity attacks." text, fixes issue #285

---

index.html

fixes issue #277
https://github.com/w3ctag/privacy-principles/issues/277
Propose that this content live in https://github.com/w3cping/privacy-request instead
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/340.html" title="Last updated on Aug 2, 2023, 4:16 PM UTC (226fc2c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/340/33d5090...226fc2c.html" title="Last updated on Aug 2, 2023, 4:16 PM UTC (226fc2c)">Diff</a>

move list of recognition techniques to a new doc

---

meetings/2023-09-tpac/tuesday-ac-meeting/slides.html

This meeting will be on [Tuesday at 15:50](https://www.w3.org/2023/09/TPAC/ac-agenda.html).
Preview at https://raw.githack.com/jyasskin/privacy-principles/tpac-ac-meeting/meetings/2023-09-tpac/tuesday-ac-meeting/slides.html.

Add TPAC AC meeting slides.

---

meetings/2023-09-tpac/breakout/slides.html

We can leave these as just titles, but it'd be best to have some bullets.
Preview at https://raw.githack.com/jyasskin/privacy-principles/favorite-slides/meetings/2023-09-tpac/breakout/slides.html.

Add breakout slides for people's favorite sections.

---

index.html

purpose specification principle
purpose limitation (no secondary use) principle
updated definition of secondary use
resolves #329
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/366.html" title="Last updated on Nov 1, 2023, 3:12 PM UTC (89caf50)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/366/5853646...89caf50.html" title="Last updated on Nov 1, 2023, 3:12 PM UTC (89caf50)">Diff</a>

purpose limitation section initial draft

---

index.html

Minor edits trying for clarity
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/364.html" title="Last updated on Oct 31, 2023, 11:17 PM UTC (30dc770)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/364/5853646...30dc770.html" title="Last updated on Oct 31, 2023, 11:17 PM UTC (30dc770)">Diff</a>

Edit section 2.5

---

index.html

Attempts to fix #351 using @npdoty's [wording](https://github.com/w3ctag/privacy-principles/issues/351#issuecomment-1768760294).
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/363.html#collective-privacy" title="Last updated on Oct 31, 2023, 9:39 PM UTC (08378cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/363/5853646...jyasskin:08378cd.html" title="Last updated on Oct 31, 2023, 9:39 PM UTC (08378cd)">Diff</a>

Don't say collective decision-making is strictly superior to engagement with individuals.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/379.html" title="Last updated on Dec 6, 2023, 5:17 PM UTC (814e846)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/379/48f13c9...814e846.html" title="Last updated on Dec 6, 2023, 5:17 PM UTC (814e846)">Diff</a>

Before section 1 editorial+reference tweaking, fixes #297

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/380.html" title="Last updated on Dec 6, 2023, 5:20 PM UTC (5ff0acb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/380/48f13c9...5ff0acb.html" title="Last updated on Dec 6, 2023, 5:20 PM UTC (5ff0acb)">Diff</a>

Improve definition of automation asymetry and simplify integration with global opt out, fix #346

---

index.html

Since @rhiaro [says](https://github.com/w3ctag/privacy-principles/pull/379#discussion_r1417696782) that's what the TAG's style guide says to do.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/387.html" title="Last updated on Dec 13, 2023, 4:58 PM UTC (d94a434)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/387/118f79e...jyasskin:d94a434.html" title="Last updated on Dec 13, 2023, 4:58 PM UTC (d94a434)">Diff</a>

lowercase the web

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/389.html" title="Last updated on Dec 13, 2023, 5:23 PM UTC (f0aad2e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/389/cddb2ec...f0aad2e.html" title="Last updated on Dec 13, 2023, 5:23 PM UTC (f0aad2e)">Diff</a>

Remove inline issue about payment, we'll write it later

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/390.html" title="Last updated on Dec 13, 2023, 9:07 PM UTC (599ce3d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/390/cd5c9c4...jyasskin:599ce3d.html" title="Last updated on Dec 13, 2023, 9:07 PM UTC (599ce3d)">Diff</a>

The Notifications section already mentions autonomy, so remove the issue about it.

---

index.html

Update Status of the Document to reflect TAG consensus on substance, and warn about editorial/restructuring.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/391.html" title="Last updated on Dec 14, 2023, 5:21 PM UTC (946936b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/391/cd5c9c4...946936b.html" title="Last updated on Dec 14, 2023, 5:21 PM UTC (946936b)">Diff</a>

Status: TAG consensus

---

index.html

Fixes #330
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/392.html" title="Last updated on Jan 17, 2024, 5:22 PM UTC (f82e887)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/392/da36b9f...f82e887.html" title="Last updated on Jan 17, 2024, 5:22 PM UTC (f82e887)">Diff</a>

Define abuse, selectively link, include in def of harassment

---

index.html

Also removed intent as Finding.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/404.html" title="Last updated on Feb 19, 2024, 10:34 AM UTC (2d894ef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/404/35dd7bf...2d894ef.html" title="Last updated on Feb 19, 2024, 10:34 AM UTC (2d894ef)">Diff</a>

SOTD fix, document now ready for wide review

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/chaals/privacy-principles/pull/407.html" title="Last updated on Feb 28, 2024, 5:21 PM UTC (1f1c723)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/407/064c571...chaals:1f1c723.html" title="Last updated on Feb 28, 2024, 5:21 PM UTC (1f1c723)">Diff</a>

minor grammar cleanup

---

index.html

Fixes #406.
@chaals, this doesn't try to fix the larger issues, but I think it handles the particular unclarity you pointed out.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/410.html" title="Last updated on Mar 13, 2024, 5:14 PM UTC (4e42ea0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/410/a203ae0...jyasskin:4e42ea0.html" title="Last updated on Mar 13, 2024, 5:14 PM UTC (4e42ea0)">Diff</a>

Clarify which data is personal data.

---

index.html

fixes #413
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/416.html" title="Last updated on Apr 24, 2024, 7:54 PM UTC (f2702e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/416/f4ada5e...f2702e2.html" title="Last updated on Apr 24, 2024, 7:54 PM UTC (f2702e2)">Diff</a>

Add labels to the principles summary

---

index.html

***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 8, 2024, 4:14 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL]([object Object])
```
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-siz …
```

mention potential tension beyond the EWP

---

index.html

***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 8, 2024, 5:17 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL]([object Object])
```
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-siz …
```

remove high level threats and reference RFC6973 instead

---

index.html

Fixes #396.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/419.html#non-retaliation" title="Last updated on May 8, 2024, 8:51 PM UTC (0bda66b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/419/ddb03c7...jyasskin:0bda66b.html" title="Last updated on May 8, 2024, 8:51 PM UTC (0bda66b)">Diff</a>

Include UAs as actors that should not retaliate.

---

index.html

Fixes #424.
@lisad, how does this look?
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/426.html" title="Last updated on Jul 3, 2024, 4:33 PM UTC (8250f27)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/426/4d1f7df...jyasskin:8250f27.html" title="Last updated on Jul 3, 2024, 4:33 PM UTC (8250f27)">Diff</a>

Link to DTI's data portability threat model.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/433.html" title="Last updated on Sep 25, 2024, 3:41 AM UTC (62ae804)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/433/0889270...jyasskin:62ae804.html" title="Last updated on Sep 25, 2024, 3:41 AM UTC (62ae804)">Diff</a>

Say who should enforcement mechanism.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/440.html" title="Last updated on Sep 28, 2024, 2:47 AM UTC (b6616e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/440/0889270...jyasskin:b6616e3.html" title="Last updated on Sep 28, 2024, 2:47 AM UTC (b6616e3)">Diff</a>

Mention tradeoffs inherent in building designed-for-purpose APIs.

---

index.html

Fixes #189.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/436.html" title="Last updated on Oct 23, 2024, 4:42 PM UTC (48a21c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/436/4337d7b...jyasskin:48a21c9.html" title="Last updated on Oct 23, 2024, 4:42 PM UTC (48a21c9)">Diff</a>

Discuss sites that users pay for with data.

---

README.md

fixes w3ctag/privacy-principles#447

update some PING references to be PrivacyWG

---

index.html

fixes w3ctag/privacy-principles#445
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/446.html" title="Last updated on Oct 25, 2024, 6:33 PM UTC (d9868cc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/446/0f96264...d9868cc.html" title="Last updated on Oct 25, 2024, 6:33 PM UTC (d9868cc)">Diff</a>

mark de-identification principal as applying to API designers

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/432.html" title="Last updated on Oct 23, 2024, 4:31 PM UTC (5cacbf7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/432/4337d7b...jyasskin:5cacbf7.html" title="Last updated on Oct 23, 2024, 4:31 PM UTC (5cacbf7)">Diff</a>

Avoid "true intent" term.

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/441.html" title="Last updated on Nov 13, 2024, 4:14 PM UTC (1753113)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/441/0889270...jyasskin:1753113.html" title="Last updated on Nov 13, 2024, 4:14 PM UTC (1753113)">Diff</a>

Mention local regulations in de-identified data section.

---

index.html

In particular that this is only a Draft finding.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/453.html#sotd" title="Last updated on Jan 7, 2025, 6:21 PM UTC (1edfd2b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/453/c8a4709...jyasskin:1edfd2b.html" title="Last updated on Jan 7, 2025, 6:21 PM UTC (1edfd2b)">Diff</a>

Remove obsolete parts of the SOTD.

---

index.html

This is a rework of the alternative text that I proposed in #457, moved to a pull request because it was starting to get unwieldy.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/459.html" title="Last updated on Mar 15, 2025, 3:56 AM UTC (97131af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/459/5206db9...97131af.html" title="Last updated on Mar 15, 2025, 3:56 AM UTC (97131af)">Diff</a>

Ancillary definition
