w3ctag/privacy-principles

README.md
Suggesting two new sets of experts for the constituencies section.
Behavioral economists: The behavioral economics of advertising is more complicated that it looks. Most of the web advertising literature focuses on a relatively simple data-for-content exchange, similar to how the reader of a controlled circulation magazine would fill out a survey about all the stuff they're responsible for buying at their company in order to receive a free subscription. This is one model for one kind of advertising, but doesn't capture other kinds of exchanges, particularly the incentives of users to supply, conceal, or misrepresent their personal information, or the incentives to actually pay attention to different ad formats.
User researchers: The more we learn about user privacy preferences, the more …
=> Additional constituencies for README.md

README.md
Make "input documents" and "related documents" in the README.md into headers, to make it easier to link to the sections directly
=> Add headers in README

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/19.html" title="Last updated on Jul 7, 2021, 11:50 PM UTC (c084256)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/19/3e89277...jyasskin:c084256.html" title="Last updated on Jul 7, 2021, 11:50 PM UTC (c084256)">Diff</a>
=> Remove noexport attributes left over from Bikeshed import.

Makefile
I'm trying to make it so that simply typing 'make' in this directory does whatever it needs to do to produce a snapshot, just like the TAG's other documents. I've only tested this Makefile on macOS. Could someone test it on Linux? And if any of us live on Windows, could you update it to work there?
=> Add Makefile rules for building a snapshot with respec on the command line.

index.html
I tried to apply the style guide to the abstract, as per #15.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/29.html" title="Last updated on Aug 11, 2021, 4:52 PM UTC (d04ecd3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/29/76c14bc...d04ecd3.html" title="Last updated on Aug 11, 2021, 4:52 PM UTC (d04ecd3)">Diff</a>
=> Rewrite the abstract to align with the style guide

index.html
This improves #1 .
This incorporates some ideas from https://github.com/asankah/identity-domains,
which distinguishes separate profiles and boundaries a user creates by clearing
cookies/storage. This covers one of the things @sandandsnow wanted to be sure to cover, but I think I forgot a second thing.
It explicitly says that browsers are free to separate contexts more finely than
this default, which I hope covers @pes10k's concern in this area. We should add a general statement about browsers being free to more-aggressively protect their users in a separate PR.
It drops the blanket statement that automating recognition is always
inappropriate, as all webservers are automated, and sometimes users intend to
present the same identity in multiple contexts.
It also removes the explicit mention …
=> Rewrite the identity section to try to define the default enforceable privacy/contextual boundary.

index.html
Also broaden Data Compromise to include non-stored data.
Fixes #27.
We might instead want to modify Correlation and Identification to include these
threats.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/37.html#principles" title="Last updated on Sep 1, 2021, 5:12 PM UTC (0c3fccc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/37/9bf9bae...jyasskin:0c3fccc.html" title="Last updated on Sep 1, 2021, 5:12 PM UTC (0c3fccc)">Diff</a>
=> Add Singling Out and Profiling to the high level threats.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/57.html" title="Last updated on Oct 6, 2021, 4:02 PM UTC (1452eb5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/57/ace2c5a...1452eb5.html" title="Last updated on Oct 6, 2021, 4:02 PM UTC (1452eb5)">Diff</a>
=> Improve the style of the one graf in Definitions

index.html
This tries to fix half of #34.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/40.html#hl-recognition-cross-context" title="Last updated on Oct 6, 2021, 4:29 PM UTC (4d02e3b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/40/b01f37b...jyasskin:4d02e3b.html" title="Last updated on Oct 6, 2021, 4:29 PM UTC (4d02e3b)">Diff</a>
=> Refine the cross-context recognition threats now that the #identity section defines the concept.

index.html
This brings all the sections to the root, to fix #75. It required a few changes beyond header levels:
* The definitions section had a paragraph acknowledging a debt to some of the definitions in DNT. I moved that to a new Acknowledgements appendix. (I had to use HTML because I don't know how to put classes on MD headings.)
* The "Privacy Principles" section (as flagged in #70) is renamed "High-Level Threats" and talks about the sections that follow.
* Since I was already making an Acks section, I filled it out.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/76.html" title="Last updated on Nov 9, 2021, 3:06 PM UTC (b28f402)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/76/75e1d19...b28f402.html" title="Last updated on …
=> Flatten and add acks

index.html
This caption does not appear to make sense without the original meme
image.  Save for the meme version of this document.
Refs #58
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/82.html" title="Last updated on Nov 10, 2021, 3:49 PM UTC (b76b4a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/82/93f2357...b76b4a3.html" title="Last updated on Nov 10, 2021, 3:49 PM UTC (b76b4a3)">Diff</a>
=> Remove leftover caption from meme

index.html
The only place that mentions it does so to say that it's *not* invoking the Vegas Rule, so we can shorten the document by just leaving it out.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/77.html#parties" title="Last updated on Dec 1, 2021, 5:13 PM UTC (e5b5cc7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/77/4056f53...jyasskin:e5b5cc7.html" title="Last updated on Dec 1, 2021, 5:13 PM UTC (e5b5cc7)">Diff</a>
=> Remove the Vegas Rule

index.html
In particular, crash reporting, use counters, and similar telemetry only
benefit users in aggregate, which doesn't satisfy the original wording here.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/78.html#dfn-duty-of-loyalty" title="Last updated on Nov 5, 2021, 4:42 AM UTC (74d4ed4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/78/75e1d19...jyasskin:74d4ed4.html" title="Last updated on Nov 5, 2021, 4:42 AM UTC (74d4ed4)">Diff</a>
=> Allow UA behavior that only indirectly benefits the user.

index.html
My thought here is that offline data sharing between contexts, even contexts with very different norms, happens all the time, and the people who do it are just careful to avoid breaking the norms of the context they got the data from. Online, the norms of two different contexts could easily be similar enough to allow a lot of cross-context use without breaking any user expectations or preferences.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/80.html#contexts-and-privacy" title="Last updated on Nov 24, 2021, 5:31 PM UTC (b464961)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/80/4056f53...jyasskin:b464961.html" title="Last updated on Nov 24, 2021, 5:31 PM UTC (b464961)">Diff</a>
=> Say that careful cross-context data sharing can be appropriate.

index.html
Via a mix of exporting some, merging synonyms into a single definition, and
removing the `<dfn>` for others.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/96.html" title="Last updated on Jan 12, 2022, 8:06 PM UTC (6e1afad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/96/b6b5dfc...jyasskin:6e1afad.html" title="Last updated on Jan 12, 2022, 8:06 PM UTC (6e1afad)">Diff</a>
=> Fix Respec warnings about unused definitions.

index.html
Should fix the first comment in #92, per today's meeting. Did I get this right? 
cc @mnot
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/99.html" title="Last updated on Jan 12, 2022, 8:27 PM UTC (e73221c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/99/36e9b27...jyasskin:e73221c.html" title="Last updated on Jan 12, 2022, 8:27 PM UTC (e73221c)">Diff</a>
=> Change "about" back to "related to" in definition of "personal data".

index.html
Use an example that makes it clear that the concern is information usage norms, not just annoying user experience.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/100.html" title="Last updated on Jan 12, 2022, 8:38 PM UTC (bad1d48)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/100/36e9b27...bad1d48.html" title="Last updated on Jan 12, 2022, 8:38 PM UTC (bad1d48)">Diff</a>
=> Example of an information sharing norm

index.html
Respec now requires this in order to use W3C styles, since
https://github.com/w3c/respec/pull/3979.
Please double-check that it actually makes sense to mark this as a TAG
document.
The other respec error is filed as https://github.com/w3c/respec/issues/3994.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/117.html" title="Last updated on Jan 31, 2022, 8:08 PM UTC (7da117d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/117/a19b13e...jyasskin:7da117d.html" title="Last updated on Jan 31, 2022, 8:08 PM UTC (7da117d)">Diff</a>
=> Add a w3c group (tag) to the document.

index.html
Respec added a markup layer between the section and the h2...
@darobin, did I get the fix right?
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/125.html" title="Last updated on Feb 9, 2022, 6:03 PM UTC (f580632)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/125/f96eaf2...jyasskin:f580632.html" title="Last updated on Feb 9, 2022, 6:03 PM UTC (f580632)">Diff</a>
=> Find the h2 inside the bp-summary.

index.html
Expanding on a list of generally accepted data rights (or subject data rights) from various laws and earlier reports. Provided some context or explanation for each. Added references (including the HEW report, one of the first privacy principles reports).
Open question (marked as such in the text) on a right to be free from automated decision-making of certain kinds (as found in the GDPR, and one of the motivations for FIPPs in the 1970s) -- can we give examples? how does this apply to the Web?
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/136.html#data-rights" title="Last updated on Mar 25, 2022, 4:23 PM UTC (0b41048)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/136/d2fc9ca...0b41048.html" title="Last updated on …
=> expanding section on data rights

index.html
A question came up related to privacycg/first-party-sets#56, and we hadn't rewritten this definition since we redefined "party" in #44, so I took a stab at simplifying this too.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/139.html#parties" title="Last updated on Apr 1, 2022, 12:05 AM UTC (eef9f85)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/139/e351f39...jyasskin:eef9f85.html" title="Last updated on Apr 1, 2022, 12:05 AM UTC (eef9f85)">Diff</a>
=> Refine and clarify the definitions of first and third parties.

index.html
Trying to make clear that party-ness and ownership (which can be complex) are not necessarily the same.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/144.html" title="Last updated on Apr 14, 2022, 1:54 AM UTC (23a5a30)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/144/ff66160...23a5a30.html" title="Last updated on Apr 14, 2022, 1:54 AM UTC (23a5a30)">Diff</a>
=> Modify two instances of "own"

index.html
Related to the concept in PR #166 this calls out some less common characteristics which the user doesn't explicitly provide, but which should be accounted for when attempting to produce a private identity for the user when they do not wish to share anything about themselves in particular contexts.
cc @jyasskin since this one will be related to the original issue as well
***
<a href="https://pr-preview.s3.amazonaws.com/kdenhartog/privacy-principles/pull/167.html" title="Last updated on Jun 22, 2022, 4:09 PM UTC (70fa574)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/167/baea919...kdenhartog:70fa574.html" title="Last updated on Jun 22, 2022, 4:09 PM UTC (70fa574)">Diff</a>
=> add additional characteristics used to identify users

index.html
Adding this to the introduction where information flows and actors/parties are first addressed, but could be included elsewhere, perhaps in a step-by-step process for identifying information flows and privacy threats.
starts to address #161
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/185.html#dfn-information" title="Last updated on Oct 25, 2022, 9:07 PM UTC (2438767)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/185/a978fa0...2438767.html" title="Last updated on Oct 25, 2022, 9:07 PM UTC (2438767)">Diff</a>
=> introducing the different parties in information flows and the different threats

index.html
There were two highlighted 'principles' in this section, but the second felt like a more specific re-stating of the high level principle. I moved the primary principle to the very start, and integrated text from the second into the supporting prose.
Language and concepts related to cross-context recognition, cross-site recognition and same-site recognition was scattered throughout the top level section and the two subsections ("Same-site recognition" and "Unwanted cross-site recognition"). I've integrated and de-duped the language, and provided dfns for cross-site and same-site recognition.
There was a lot of language in the "Same-site recognition" subsection about fingerprinting, so I've turned this into a subsection on fingerprinting instead, as this might be a handy reference point.
In …
=> Editorial pass on Identity principle

index.html
addresses #174 
Revisions off of #181, to emphasize that APIs should be designed so that they do not assert or promise on the user's behalf, and that sites should include deception in their threat modeling, as it's likely to happen for a variety of reasons.
Still includes, in some cases, user agents supporting the ability of a user to provide information that may not be factually correct.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/191.html#support-choosing-info" title="Last updated on Nov 3, 2022, 11:05 PM UTC (b9e5200)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/191/caf9e8b...b9e5200.html" title="Last updated on Nov 3, 2022, 11:05 PM UTC (b9e5200)">Diff</a>
=> no-assertion

index.html
Intended to fix #157.
@IreneKnapp, how does this look?
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/203.html#guardians" title="Last updated on Dec 14, 2022, 5:08 PM UTC (e77bd36)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/203/94428dc...jyasskin:e77bd36.html" title="Last updated on Dec 14, 2022, 5:08 PM UTC (e77bd36)">Diff</a>
=> Add a section on guardians

index.html
While writing this, I concluded that the "guardians" section belongs inside the vulnerable-people section, so I kept this focused on device owners.
Fixes #2.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/202.html#device-administrators" title="Last updated on Dec 14, 2022, 5:11 PM UTC (8046e06)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/202/fca8866...jyasskin:8046e06.html" title="Last updated on Dec 14, 2022, 5:11 PM UTC (8046e06)">Diff</a>
=> Explain how to balance device owner vs user rights.

index.html
There was a comment in the source that our definition of "context" used "purpose" with a different meaning from the processing-related definition we give it. While trying to clarify our definition, I realized that Dr. Nissenbaum doesn't define "context" anywhere in [Privacy as Contextual Integrity](https://digitalcommons.law.uw.edu/cgi/viewcontent.cgi?article=4450&context=wlr), and I haven't read the books in her citation 67 to find a definition in them. Since she does say it's "firmly rooted in common experience", I tried to use my common experience to explain what we mean.
I think contexts aren't actually divided by the people in them having different reasons to be in the different contexts, but rather just by the people feeling like the contexts are different.
***
<a …
=> Refine the definition of "context" to avoid re-using "purpose".

index.html
Fixes #209.
Our introduction of "first party" is a little awkward in https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/213.html#parties. I'd like to deal with that along with #152, in a separate PR.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/213.html" title="Last updated on Jan 18, 2023, 12:39 AM UTC (f4914b4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/213/0fc6c64...jyasskin:f4914b4.html" title="Last updated on Jan 18, 2023, 12:39 AM UTC (f4914b4)">Diff</a>
=> Replace most uses of "party" with "actor", except for 1P, 3P, and 🥳.

index.html
Clarify language on access right to make it explicit that databases must not be kept secret and people must have the meaningful ability to discover what actors are collecting what data about them.
Clarification was noted as a need in #156, which this PR is intended to address.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/219.html#data-rights" title="Last updated on Jan 27, 2023, 1:08 AM UTC (ad0a535)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/219/d9fd32a...ad0a535.html" title="Last updated on Jan 27, 2023, 1:08 AM UTC (ad0a535)">Diff</a>
=> Discovery 156

index.html
I haven't touched the Recognition Methods section in this PR.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/218.html#identity" title="Last updated on Feb 15, 2023, 5:20 PM UTC (e770f42)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/218/d9fd32a...jyasskin:e770f42.html" title="Last updated on Feb 15, 2023, 5:20 PM UTC (e770f42)">Diff</a>
=> Simplify and remove redundant text in the Identity section.

index.html
@yoavweiss was worried that the existing wording put constraints on Web Perf APIs that it didn't put on alternate ways the platform exposes the same data. We think changing this word avoids the problem.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/222.html" title="Last updated on Feb 27, 2023, 5:32 PM UTC (0247538)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/222/cbadea7...jyasskin:0247538.html" title="Last updated on Feb 27, 2023, 5:32 PM UTC (0247538)">Diff</a>
=> Change 'send' to 'expose' in the ancillary data section.

index.html
While advertisers can easily buy ads in particular publications to
target groups of users, a researcher can look at the content of those
publications to see the same content that's shown to all readers.
Online, each visitor can see a different set of ads, so we need other
mechanisms to help researchers discover problems. Web standards can
define those mechanisms.
This tries to fix #235. How'd I do, @michaelkleber?
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/248.html#collective" title="Last updated on Apr 12, 2023, 4:50 PM UTC (cda2b1b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/248/4b06c6c...jyasskin:cda2b1b.html" title="Last updated on Apr 12, 2023, 4:50 PM UTC (cda2b1b)">Diff</a>
=> Identify what makes print less likely to violate group privacy than the web.

index.html
The text I originally wrote here got interpreted as saying that services
have to explain all the details of how they use data to fight fraud,
which of course would help the fraudsters avoid detection. Instead, we
meant just that the service should say what kinds of things it's
collecting in order to protect people.
I also got a comment on how abrupt this paragraph is, since it just
restricts the safety-related data collection without saying that this
purpose is reasonable in the first place.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/249.html" title="Last updated on Apr 12, 2023, 4:50 PM UTC (3f4b834)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/249/4b06c6c...jyasskin:3f4b834.html" title="Last updated on Apr …
=> Avoid saying that safety systems have to describe how to exploit them.

index.html
I found a couple of places where "JavaScript" isn't capitalised correctly.
***
<a href="https://pr-preview.s3.amazonaws.com/chrisn/privacy-principles/pull/259.html" title="Last updated on Apr 24, 2023, 7:35 PM UTC (92748f5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/259/4e4732c...chrisn:92748f5.html" title="Last updated on Apr 24, 2023, 7:35 PM UTC (92748f5)">Diff</a>
=> Fix capitalisation of JavaScript

index.html
Fixes #260.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/264.html" title="Last updated on May 3, 2023, 11:51 PM UTC (25d2902)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/264/6b09507...jyasskin:25d2902.html" title="Last updated on May 3, 2023, 11:51 PM UTC (25d2902)">Diff</a>
=> Avoid defining "principles" with a different meaning than in the title of the document.

index.html
This is intended as a replacement for #236 and a fix for #229.
This:
- Makes it clear that it's processing and not purposes that are sensitive.
- Keeps the language about actors that #236 added.
- Removes "burden of proof" and replaces it with a brief description of risk assessment. (I don't think we want to go into details about impact assessment methodologies.)
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/242.html" title="Last updated on May 31, 2023, 4:10 PM UTC (b4f1d6d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/242/b232917...b4f1d6d.html" title="Last updated on May 31, 2023, 4:10 PM UTC (b4f1d6d)">Diff</a>
=> Processing is sensitive, not purposes

index.html
That comma annoyed me.  I think that this is better.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/privacy-principles/pull/286.html" title="Last updated on Jun 27, 2023, 6:56 AM UTC (39ec4b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/286/5286a4e...martinthomson:39ec4b9.html" title="Last updated on Jun 27, 2023, 6:56 AM UTC (39ec4b9)">Diff</a>
=> Grammar fix

index.html
The notion that fingerprinting might not be economically feasible doesn't really help anyone.  On the one hand, it just tends to create an excuse for lazy web designers who might choose to neglect fingerprinting protection on the basis that "it won't be viable to exploit this" (tip: it probably is viable).  On the other, the admonition about people who didn't ask to be treated that way is already implied.y
Also, the document has enough words in it already.  No point playing both sides here.
I considered saying something more in place of this, but the paragraph is already complete as is.  That is, it talks about the challenges inherent with fingerprinting in that it disproportionately affects those smaller groupings that tend to form around less mainstream choices or characteristics.
*** …
=> No excuses for fingerprinting

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/295.html" title="Last updated on Jun 28, 2023, 3:32 PM UTC (a05161c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/295/86d1c1f...a05161c.html" title="Last updated on Jun 28, 2023, 3:32 PM UTC (a05161c)">Diff</a>
=> Encourage purpose-built APIs, fix #175

index.html
addresses #24
related to #135
note that consent does not imply consent of people other than the user
add principle to consent section that functionality must be provided to access or remove data in non-user cases
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/287.html" title="Last updated on Jun 30, 2023, 8:15 PM UTC (f4c7d7e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/287/5286a4e...f4c7d7e.html" title="Last updated on Jun 30, 2023, 8:15 PM UTC (f4c7d7e)">Diff</a>
=> principle for non-user privacy, to be able to access and remove data uploaded by others

index.html
Post-processing replaced the title of the `bp-summary` title in the body of the text but not in the table of contents.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/privacy-principles/pull/320.html" title="Last updated on Jul 2, 2023, 7:50 AM UTC (51b80f8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/320/077d2a9...tidoust:51b80f8.html" title="Last updated on Jul 2, 2023, 7:50 AM UTC (51b80f8)">Diff</a>
=> Adjust "bp-summary" title in table of contents too

index.html
Simplify the fake consent problem, new language
Fixes #192
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/290.html" title="Last updated on Jul 5, 2023, 2:43 PM UTC (3551c2d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/290/86d1c1f...3551c2d.html" title="Last updated on Jul 5, 2023, 2:43 PM UTC (3551c2d)">Diff</a>
=> Principle on fake consent

index.html
Moves extra text about context to a Context section in the Common Concepts appendix.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/322.html" title="Last updated on Jul 5, 2023, 4:15 PM UTC (a26e28a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/322/077d2a9...a26e28a.html" title="Last updated on Jul 5, 2023, 4:15 PM UTC (a26e28a)">Diff</a>
=> Copy edit Section 2 intro, fixes #302.

index.html
Moves Recognition definition and subsections into its own section in the Common Concepts appendix.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/323.html" title="Last updated on Jul 12, 2023, 4:11 PM UTC (3930eca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/323/077d2a9...3930eca.html" title="Last updated on Jul 12, 2023, 4:11 PM UTC (3930eca)">Diff</a>
=> 302 edit identity

index.html
addresses #251 
This covers both:
* revealing data about a small group of people affects individual privacy even without individualized data (revealing to a teacher that a student in the class looked up a particular health condition)
* targeting messages to a small group of people (showing a message just to people who visited a particular Planned Parenthood clinic, or who are empaneled on a jury)
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/289.html" title="Last updated on Jun 27, 2023, 10:14 PM UTC (d53e53c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/289/5286a4e...d53e53c.html" title="Last updated on Jun 27, 2023, 10:14 PM UTC (d53e53c)">Diff</a>
=> potential small group privacy examples

index.html
noting that low-granularity information can still reveal precise information
and some of the conditions for why
less emphatic about the sensitivity difference
fixes #281 (intended to, anyway)
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/339.html" title="Last updated on Aug 1, 2023, 6:17 PM UTC (8f7ddf5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/339/33d5090...8f7ddf5.html" title="Last updated on Aug 1, 2023, 6:17 PM UTC (8f7ddf5)">Diff</a>
=> Cite RFC6772

index.html
Unwanted Information and Harassment seemed to be saying a lot of the same things. I've merged the principles, but retained the definitions. Renamed the section to "Abuse". I feel it shortens and simplifies things, but interested to hear what others think. Let me know if I lost anything. 
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/328.html#abuse" title="Last updated on Aug 23, 2023, 4:16 PM UTC (b10c5cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/328/077d2a9...b10c5cd.html" title="Last updated on Aug 23, 2023, 4:16 PM UTC (b10c5cd)">Diff</a>
=> Harrasment, for #310 and #311

index.html
Distills several principles into a single one at the start. Ancillary Data subsection may now be better as part of explanatory text in the intro or appendix (but haven't got to them yet, will revisit later).
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/324.html" title="Last updated on Sep 6, 2023, 4:19 PM UTC (e6160ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/324/aa0bb95...e6160ff.html" title="Last updated on Sep 6, 2023, 4:19 PM UTC (e6160ff)">Diff</a>
=> Editorial: data minimization, fixes #303.

index.html
Condenses section into a single principle, with explanations. Removes many words.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/325.html" title="Last updated on Sep 6, 2023, 4:29 PM UTC (fed1cbb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/325/077d2a9...fed1cbb.html" title="Last updated on Sep 6, 2023, 4:29 PM UTC (fed1cbb)">Diff</a>
=> Editorial: Information Access, fixes #304

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/334.html" title="Last updated on Sep 6, 2023, 4:47 PM UTC (ae69e43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/334/e3bc7fb...ae69e43.html" title="Last updated on Sep 6, 2023, 4:47 PM UTC (ae69e43)">Diff</a>
=> Editorial pass, 1. to 1.1.2 (fixes #298)

index.html
And add a preProcess function to error if we forget to maintain these lists.
This fixes half of #343.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/355.html" title="Last updated on Oct 11, 2023, 5:24 PM UTC (a02175d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/355/2e72917...jyasskin:a02175d.html" title="Last updated on Oct 11, 2023, 5:24 PM UTC (a02175d)">Diff</a>
=> Record a target audience for each principle.

index.html
Fixes #345, according to the discussion at https://github.com/w3ctag/privacy-principles/blob/main/meetings/2023-10-25-minutes.md#345-vulnerability.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/367.html#vulnerability" title="Last updated on Nov 7, 2023, 10:26 PM UTC (43146f0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/367/6874866...jyasskin:43146f0.html" title="Last updated on Nov 7, 2023, 10:26 PM UTC (43146f0)">Diff</a>
=> Remove the vulnerability principle, and move the section to Section 1.

index.html
Mostly this consisted of using "administrator" instead of "device
administrator", and I added a sentence saying that UAs sometimes assign
an administrator based on the user's account.
Fixes #353. @reillyeon, how does this look?
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/368.html#device-administrators" title="Last updated on Nov 15, 2023, 5:15 PM UTC (0dafa68)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/368/7dd3a4f...jyasskin:0dafa68.html" title="Last updated on Nov 15, 2023, 5:15 PM UTC (0dafa68)">Diff</a>
=> Separate device administrators from UA administrators.

index.html
This is a replacement for #359 after the discussion in https://github.com/w3ctag/privacy-principles/blob/main/meetings/2023-10-04-minutes.md. It will close #220.
@pes10k, I think I fixed your [comments](https://github.com/w3ctag/privacy-principles/pull/359#issuecomment-1747625487):
* "identifiable person" was an echo of a phrase in the [definition of "personal data"](https://w3ctag.github.io/privacy-principles/#dfn-data), but I found a way to avoid it.
* I replaced the CSP report example with event timings. There's also a nit there that the [duration](https://www.w3.org/TR/event-timing/#priv-sec) field is a novel piece of data, so I could narrow this to just the [`processingEnd`](https://www.w3.org/TR/event-timing/#dom-performanceeventtiming-processingend) field.
* I reworded the "it …
=> Rewrite ancillary uses to focus on 2 kinds of ancillary APIs rather than ancillary data.

index.html
Fixes #317, because I think we've already done a pass over Recognition.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/369.html#boring-terminology" title="Last updated on Dec 5, 2023, 8:05 PM UTC (950bcf8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/369/c2806a2...jyasskin:950bcf8.html" title="Last updated on Dec 5, 2023, 8:05 PM UTC (950bcf8)">Diff</a>
=> Copy-edit the Common Concepts section, except for the Recognition sub-section.

index.html
These aren't directly connected to privacy, and we don't have evidence
that the ancillary APIs take a noticeable amount of either.
Fixes #376.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/384.html" title="Last updated on Dec 4, 2023, 5:58 PM UTC (25ca056)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/384/c2806a2...jyasskin:25ca056.html" title="Last updated on Dec 4, 2023, 5:58 PM UTC (25ca056)">Diff</a>
=> Remove mention of processing time and bandwidth.

index.html
Fixes #372.
I considered reversing the order, to start with "should follow their users' needs in deciding the default enabledness [ew] of ancillary ...", but I think the key in this principle is that users should be able to change it more easily than by switching browsers.
[Also, it's kind of amazing that we don't have a better word for the question of whether something is enabled or disabled. https://english.stackexchange.com/q/92781/122144, https://english.stackexchange.com/q/102995/122144, and https://stackoverflow.com/q/2544435/943619 don't have options I like.]
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/385.html" title="Last updated on Dec 4, 2023, 6:15 PM UTC (2028122)">Preview</a> | <a …
=> Avoid implying that ancillary APIs w/ new information should default to enabled.

index.html
Fixes #371
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/393.html" title="Last updated on Jan 17, 2024, 5:32 PM UTC (3c4e0bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/393/da36b9f...3c4e0bb.html" title="Last updated on Jan 17, 2024, 5:32 PM UTC (3c4e0bb)">Diff</a>
=> RFC2119 changes

index.html
Fixes #343
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/394.html" title="Last updated on Jan 11, 2024, 2:47 PM UTC (f26deee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/394/da36b9f...f26deee.html" title="Last updated on Jan 11, 2024, 2:47 PM UTC (f26deee)">Diff</a>
=> Adds cute little audience pills

index.html
This removes redundant text from the data minimization principle (the principle itself was repeated in the description).
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/399.html" title="Last updated on Jan 24, 2024, 9:50 AM UTC (970ae5d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/399/34140d9...970ae5d.html" title="Last updated on Jan 24, 2024, 9:50 AM UTC (970ae5d)">Diff</a>
=> Simplify data minimization

index.html
This addresses #373 -- adds some wording on vulnerable people who don't know it, and context by context vulnerability, and some links between "vulnerability" and "vulnerable people."
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/402.html" title="Last updated on Feb 14, 2024, 5:24 PM UTC (9849885)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/402/2ddef7f...9849885.html" title="Last updated on Feb 14, 2024, 5:24 PM UTC (9849885)">Diff</a>
=> Vulnerable people wording and links

index.html
#yoda
Fixes part of @chrisn's #401.
***
<a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/403.html" title="Last updated on Feb 14, 2024, 5:38 PM UTC (d019a49)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/403/75a3e3d...d019a49.html" title="Last updated on Feb 14, 2024, 5:38 PM UTC (d019a49)">Diff</a>
=> UAs should give information, not just try to.

index.html
Several grammar fixes including missing Oxford commas (Oxford comas are used throughout but there are few that were missed), correction of the use of the plural of people, and removal of an extraneous "how".
***
<a href="https://pr-preview.s3.amazonaws.com/rinchen/privacy-principles/pull/408.html" title="Last updated on Feb 28, 2024, 5:23 PM UTC (9d494f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/408/064c571...rinchen:9d494f6.html" title="Last updated on Feb 28, 2024, 5:23 PM UTC (9d494f6)">Diff</a>
=> Grammar fixes including fixing missing oxford comas.

.github/dependabot.yml
Since https://github.com/w3ctag/privacy-principles/actions/runs/8084746976 says our actions are out of date.
Editorial, but it'll cause dependabot to open PRs, so I didn't want to do it completely unilaterally.
=> Auto-update our GH Actions dependencies

index.html
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 8, 2024, 5:18 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL]([object Object])
```
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-siz …
```
=> All information may be sensitive

index.html
The checkboxes help with #354, but I'm not sure they should be considered to fix it. @dmarti?
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/443.html#principle-list" title="Last updated on Sep 30, 2024, 12:05 AM UTC (92acf10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/443/296b672...jyasskin:92acf10.html" title="Last updated on Sep 30, 2024, 12:05 AM UTC (92acf10)">Diff</a>
=> Move the list of principles to the top.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/435.html" title="Last updated on Sep 25, 2024, 4:09 AM UTC (0935302)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/435/0889270...jyasskin:0935302.html" title="Last updated on Sep 25, 2024, 4:09 AM UTC (0935302)">Diff</a>
=> Say the suggestions for handling new ancillary personal data are examples.

index.html
A quote was repeated twice in one example.
---
The specific example here seems to be two separate examples, so I'm not sure which of the redundant copies was worth keeping.  I thought it made more sense being left in the middle immediately following the relevant feature being discussed.  Potentially would be better to split the examples, not sure.
***
<a href="https://pr-preview.s3.amazonaws.com/mmocny/privacy-principles/pull/430.html" title="Last updated on Sep 16, 2024, 2:33 PM UTC (ea1b000)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/430/0889270...mmocny:ea1b000.html" title="Last updated on Sep 16, 2024, 2:33 PM UTC (ea1b000)">Diff</a>
=> Remove redundant line

index.html
Use US spelling of "labor" instead of "labour', per the W3C Manual of Style: https://www.w3.org/Guide/manual-of-style/#Spelling
***
<a href="https://pr-preview.s3.amazonaws.com/tantek/privacy-principles/pull/429.html" title="Last updated on Sep 11, 2024, 10:04 PM UTC (8b20b2b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/429/0889270...tantek:8b20b2b.html" title="Last updated on Sep 11, 2024, 10:04 PM UTC (8b20b2b)">Diff</a>
=> labour -> labor per W3C manual of style US spelling

index.html
This reverts #436 and commit 254a8d0dbf553563c5b9f7c01d4cc606a5ce6851. Some folks on the TAG objected to the change.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/451.html" title="Last updated on Nov 14, 2024, 6:30 PM UTC (10afc18)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/451/48e1a5f...jyasskin:10afc18.html" title="Last updated on Nov 14, 2024, 6:30 PM UTC (10afc18)">Diff</a>
=> Remove the endorsement of exchanging personal data for content.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/427.html" title="Last updated on Jan 8, 2025, 12:51 AM UTC (e82aab9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/427/c8a4709...jyasskin:e82aab9.html" title="Last updated on Jan 8, 2025, 12:51 AM UTC (e82aab9)">Diff</a>
=> Make all citations Camel-Case, and alphabetize them.

index.html
This doesn't fundamentally change things, but there are a few subtle differences in how this is presented.
1. It's no longer a single very long sentence.
2. The word "essential" remains attached to the text about service termination.  This remains a pivotal concept here.  I expect that reasonable people will continue to disagree with each other about the degree to which certain data is essential in specific cases.
3. I've included three somewhat general examples of retaliation.
***
<a href="https://pr-preview.s3.amazonaws.com/martinthomson/privacy-principles/pull/458.html" title="Last updated on Mar 5, 2025, 9:04 AM UTC (9c1a913)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/458/5206db9...martinthomson:9c1a913.html" title="Last updated on Mar 5, …
=> Rework retaliation text
